## API Req 1: Retrieve all the films.
   GET http://localhost:3000/api/films HTTP/1.1

## API Req 2: retrive a film given the ID
# GET http://localhost:3000/api/films/2 HTTP/1.1

## API Req 3: Create new film (without id) -- dee terminare con 3 cancelletti altimenti si rompe
# POST http://localhost:3000/api/films HTTP/1.1
# Content-Type: application/json

# {
#   "title": "scooby doo 8",
#   "favorite": 1,
#   "watchDate": "2025-02-03",
#   "rating": 4
# }
###

### API Req 4: Update film favorite property.
# PUT http://localhost:3000/api/films/1 HTTP/1.1
# content-type: application/json

# {
#     "id" : 1,
#     "favorite": 0
# }
###

### API Req 5: Change the reating
PUT http://localhost:3000/api/films/rating/delta HTTP/1.1
content-type: application/json

{
    "id" : 1,
    "operazione": "+",
    "delta": 5
}
###


### API Req 6: Deleate a film given the id
#  DELETE  http://localhost:3000/api/films/3 HTTP/1.1
#  Content-Type: application/json

# ## API Req 7: 
# # get non possono avere il body
# GET http://localhost:3000/api/films/filter/unseen HTTP/1.1
# content-type: application/json

###